### ISSUE TITLE
Add `/` indicator markers at the expected location in the COBOL AST.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#10]
The source code for `/` will be parsed and printed correctly, but the indicator is supposed to be positioned at the "top of the page." It is unclear where comments are supposed to be relocated to, but it is relatively simple through a visitor with more information.

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
