### ISSUE TITLE
Implement Paragraph and Statement on applicable model objects.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#12]
Implementing `Paragraph` and `Statement` will be required to fix the formatting rules:

- [Paragraphs and statements should be indented consistently - RSPEC-1280](https://rules.sonarsource.com/cobol/RSPEC-1280)
- [Statements should be on separate lines - RSPEC-122](https://rules.sonarsource.com/cobol/RSPEC-122)

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
