### ISSUE TITLE
Add recipe to fix RSPEC-1192: String literals should not be duplicated

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#13]
This recipe is doable today.

Rule: [String literals should not be duplicated](https://rules.sonarsource.com/cobol/RSPEC-1192)

Exceptions
Literals with fewer than 7 characters are ignored.

Only duplications located in a PROCEDURE DIVISION, not those contained in copybooks are reported.

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
