### ISSUE TITLE
Implement clean up recipe for RSPEC-1728: Data item declarations should be aligned

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#15]
This recipe is doable today IF scoped to the example in the issue.

Based on the example a data item is a `dataDescriptionEntry`.
[RSPEC-1728: Data item declarations should be aligned](https://rules.sonarsource.com/cobol/RSPEC-1728)

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
