### ISSUE TITLE
List of potentially helpful APIs for recipe authoring

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#16]
- `isCopiedSource`: a method to check if a COBOL AST element contains a marker produced by `COPY`.
    - Replaces requirement to understand the purpose each post-process marker.
- `isReplacedSource`: a method to check if a COBOL AST element contains a marker related to `REPLACE`.
    - Replaces requirement to understand the purpose each post-process marker.

Note: both copied and replaced code may be printed (viewed) as the source or the post-transformed code, with and without columns (column alignment on post-transformed code is not 100% aligned at this time).

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
