### ISSUE TITLE
Oraweb usage at Desjadins

### ISSUE THREAD

**Issue by okundzich** [moderneinc/rewrite-cobol#17]
Bonjour Stéphane,

 

Voici les fonctions que François et moi utilisons le plus. Les développeurs aussi utilisent ces fonctions.

En fait tous les analystes fonctionnels et développeurs LEF et LBA utilisent OraWeb.

 

La recherche avancée, qui permet de réduire le nombre de résultats. Un peu à a Mass Mailer 😊
![image](https://user-images.githubusercontent.com/26604045/207124784-6722be5a-72a4-49ac-8eb5-f425661f2c4f.png)

![image](https://user-images.githubusercontent.com/26604045/207124834-5302d973-763b-4a8a-a8f3-897ae5b1c707.png)

Dans les résultats, nous utilisons principalement les fonctions encadrées.

![image](https://user-images.githubusercontent.com/26604045/207124919-9326a8b3-cc37-4852-80bf-f7e67d4d5047.png)
Dans les résultats, la fonction « Expanded » est particulièrement utile, puisqu’elle importe les copybooks dans le code.
![image](https://user-images.githubusercontent.com/26604045/207124961-77871a40-97a7-4370-9d9a-7955913da3f5.png)

La fonction « Call Tree » est aussi utile.
![image](https://user-images.githubusercontent.com/26604045/207125036-60b114da-96ad-45b2-be30-69b629e9e011.png)

La fonction « Flowchart » nous donne un aperçu du programme.
![image](https://user-images.githubusercontent.com/26604045/207125108-8c58aef3-9abb-4719-aaaf-dd9ba921d1ba.png)

Ce qui est très bien, c’est que les menus sont contextuels. Chaque type de composante a une liste de fonctions qui lui est propre.

 

Nous faisons des recherches pour du Cobol, du Java, du Web et pour des workflow DataStage.

OraWeb est un outil indispensable dans notre quotidien.

 

Bonne journée,

**Comment by okundzich** [comment]
Hello Stephane,

 

Here are the functions that François and I use the most. Developers also use these functions.

In fact all functional analysts and LEF and LBA developers use OraWeb.

 

The advanced search, which allows you to reduce the number of results. A bit like a Mass Mailer 😊

In the results, we mainly use the boxed functions.

In the results, the “Expanded” function is particularly useful, since it imports the copybooks into the code.

The "Call Tree" function is also useful.

The “Flowchart” function gives us an overview of the program.

What is very good is that the menus are contextual. Each type of component has its own list of functions.

 

We do research for Cobol, Java, Web and DataStage workflows.

OraWeb is an indispensable tool in our daily lives.

 

Have a good day,

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
