### ISSUE TITLE
A list of implementation details that may not be completely correct yet.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#5]
### Problem

COBOL is a very large language with a lot of details and there is not much public code.
This issue serves as a reminder about various possible gaps related to unknowns in the preprocessing and parsing of COBOL.

### PreprocessReplaceVisitor

- The original word is saved in the Replace marker, which allows multiple replacements to occur from other `ReplaceClause`(s).
- Replace markers are only added to changed words, but it may be necessary to mark all of the matched words.
- The original rule that triggered the replacement is not retained in the Replace marker. The original rule may be necessary, but it had been left out for simplicity.

### Printers

- Printing the POST processed source with column areas is not fully aligned. It is possible to retain alignment but was not a priority. We may add POST processed alignment upon request.

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
