### ISSUE TITLE
Convert CommentLines to a List of Word to enable single word search results.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#52]
COBOL searches in comments are helpful for analysts, and many investigations are by program name (keyword).

CommentLines are already separated from the COBOL tree and are easily searchable/non-searchable based on an `Option.` Converting the CommentLines to a list of words will enable specific search results on particular terms.

**Comment by sjungling** [comment]
Issue older than 1 year. Reopen if still needed
