### ISSUE TITLE
Update JclParserVisitor with whitespace rules.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#64]
Currently, `sourceBefore` and `indexOfNextNonWhitespace` do not contain the appropriate rules to set cursor positions in the source. Similar to COBOL, JCL has a specific syntax to communicate the continuations of statements.

#58 will add a JCL line reader to preserve the source code.
After #58, update the methods `sourceBefore` and `indexOfNextNonWhitespace` to function with JCL.

**Comment by sjungling** [comment]
Issue older than 1 year. Reopen if still needed
