### ISSUE TITLE
Fully implement Copy REPLACING and ReplaceArea REPLACE rules via language specifications.

### ISSUE THREAD

**Issue by traceyyoshima** [moderneinc/rewrite-cobol#8]
### Problem

The Replacement rules have not been fully implemented, since we do not know exactly what the expected changes are.

A few examples:
- There are specific rules for debugging lines (indicator D or d) that are not handled.
- Keywords `LEADING` and `TRAILING` are not implemented.

More info may be found in the IBM z/OS Language Reference, Chapter 112. Compiler-directing statements.
Section: COPY statement and REPLACE statement.

**Comment by sjungling** [comment]
Older than 1 year. Not prioritized at this time. Reopen if still needed.
